<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sCentral Image Service%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sCentral Image Service%s.')) ?></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('1st Block') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('This is the first Block')) ?></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('1st Block') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('This is the first Block')) ?></p>
            </div>
        </div>
    </div>
    
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('1st Block') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('This is the first Block')) ?></p>
            </div>
        </div>
    </div>
</div>
